apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebserver
  namespace: yat2
  labels:
    app: staticwebserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticwebserver
  template:
    metadata:
      labels:
        app: staticwebserver
    spec:
      containers:
        - name: staticwebserver
          image: DOCKERHUB_USERNAME/DOCKERHUB_REPOSITORY:IMAGE_LABEL
          ports:
            - containerPort: 8080
          env:
            - name: RUNENVIRONMENT
              value: Production
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  namespace: yat2
  name: staticwebserver-service
  labels:
    app: staticwebserver
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: staticwebserver
  sessionAffinity: None