# This section will create a secret in the Kubernetes cluster.
# We need this for private docker repos.
apiVersion: v1
kind: Secret
metadata:
  name: regcred2
data:
  .dockerconfigjson: DOCKER_CONFIG
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygobackend
  namespace: yat2
  labels:
    app: mygobackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygobackend
  template:
    metadata:
      labels:
        app: mygobackend
    spec:
      containers:
        - name: mygobackend
          image: DOCKERHUB_USERNAME/DOCKERHUB_REPOSITORY:IMAGE_LABEL
          ports:
            - containerPort: 8080
          env:
            - name: RUNENVIRONMENT
              value: Production
      imagePullSecrets:
      - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  namespace: yat2
  name: mygobackend-service
  labels:
    app: mygobackend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mygobackend
  sessionAffinity: None